image: maven:3-jdk-8

stages:
  - build
  - test

#build:
#  script: "mvn clean install -B"

job_java_mr:
    stage: build
    script:
      - "mvn clean install -B"
      - "echo 'Total: ' && grep -o -P '[0-9]+%' jacoco-report/target/site/jacoco-aggregate/index.html | head -n1 "
    only:
        - +refs/merge-requests/*/head:refs/remotes/origin/merge-requests/*
        - /^(epmrd|issue)-.*$/@viacheslav_tradunskyi/rd-management-system
#    except:
#        - master@viacheslav_tradunskyi/rd-management-system
#    tags:
#        - java/ui-docker
